name: Deploy to S3

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 레포지토리 클론
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. AWS CLI 설정
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. S3 버킷에 파일 업로드
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://bongjinifrontendbukkit  --delete
